//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Presentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SMS_Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMS_Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS_Presentation.App_Start.SMS_Mensagens", typeof(SMS_Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail invalido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login não cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta bloqueado. Entre em contato com o administrador do sistema para executar o desbloqueio.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario ja efetuou um login com a senha provisoria. Favor gerar outra senha.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero de falhas de login superior ao limite diario de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais invalidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao pode ser igual a anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua pesquisa não retornou nenhum resultado - Tente outras opções de pesquisa.
        /// </summary>
        internal static string M0010 {
            get {
                return ResourceManager.GetString("M0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem acesso a essa funcionalidade.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado mas sem acesso ao sistema. Consulte a administração..
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de conclusão inferior a data de cadastro.
        /// </summary>
        internal static string M0013 {
            get {
                return ResourceManager.GetString("M0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de conclusão maior que a data corrente.
        /// </summary>
        internal static string M0014 {
            get {
                return ResourceManager.GetString("M0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro atendeu ao filtro especificado.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum arquivo selecionado.
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extensão de arquivo não suportada.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do arquivo muito longo.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor já cadastrado.
        /// </summary>
        internal static string M0026 {
            get {
                return ResourceManager.GetString("M0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse fornecedor. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0027 {
            get {
                return ResourceManager.GetString("M0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone já cadastrado.
        /// </summary>
        internal static string M0028 {
            get {
                return ResourceManager.GetString("M0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente já cadastrado.
        /// </summary>
        internal static string M0029 {
            get {
                return ResourceManager.GetString("M0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse cliente. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0030 {
            get {
                return ResourceManager.GetString("M0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Centro de Custo já cadastrado. Já existem um centro de custo com os mesmos grupo, subgrupo e número..
        /// </summary>
        internal static string M0036 {
            get {
                return ResourceManager.GetString("M0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse centro de custo. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0037 {
            get {
                return ResourceManager.GetString("M0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco já cadastrado.
        /// </summary>
        internal static string M0038 {
            get {
                return ResourceManager.GetString("M0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse banco. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0039 {
            get {
                return ResourceManager.GetString("M0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa conta bancária. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0040 {
            get {
                return ResourceManager.GetString("M0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta bancária já cadastrada.
        /// </summary>
        internal static string M0041 {
            get {
                return ResourceManager.GetString("M0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial já cadastrada.
        /// </summary>
        internal static string M0042 {
            get {
                return ResourceManager.GetString("M0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa Filial. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0043 {
            get {
                return ResourceManager.GetString("M0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0044 {
            get {
                return ResourceManager.GetString("M0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse grupo. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0045 {
            get {
                return ResourceManager.GetString("M0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SubGrupo já cadastrado.
        /// </summary>
        internal static string M0046 {
            get {
                return ResourceManager.GetString("M0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse Subgrupo. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equipamento já cadastrado.
        /// </summary>
        internal static string M0048 {
            get {
                return ResourceManager.GetString("M0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse equipamento. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0049 {
            get {
                return ResourceManager.GetString("M0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transportadora já cadastrada.
        /// </summary>
        internal static string M0050 {
            get {
                return ResourceManager.GetString("M0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no envio do SMS.
        /// </summary>
        internal static string M0051 {
            get {
                return ResourceManager.GetString("M0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SMS enviado com sucesso.
        /// </summary>
        internal static string M0052 {
            get {
                return ResourceManager.GetString("M0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa transportadora. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0053 {
            get {
                return ResourceManager.GetString("M0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto já cadastrado.
        /// </summary>
        internal static string M0054 {
            get {
                return ResourceManager.GetString("M0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse produto. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0055 {
            get {
                return ResourceManager.GetString("M0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa forma de pagamento. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0056 {
            get {
                return ResourceManager.GetString("M0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta a Pagar já cadastrada.
        /// </summary>
        internal static string M0057 {
            get {
                return ResourceManager.GetString("M0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tarefa ja cadastrada.
        /// </summary>
        internal static string M0058 {
            get {
                return ResourceManager.GetString("M0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse lançamento. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0059 {
            get {
                return ResourceManager.GetString("M0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de inicio de parcelamento menor que a data corrente.
        /// </summary>
        internal static string M0060 {
            get {
                return ResourceManager.GetString("M0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero de parcelas menor do que 2.
        /// </summary>
        internal static string M0061 {
            get {
                return ResourceManager.GetString("M0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento recorrente não pode ser parcelado.
        /// </summary>
        internal static string M0062 {
            get {
                return ResourceManager.GetString("M0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma conta bancária definida como conta principal. Não pode haver duas contas nessa situação..
        /// </summary>
        internal static string M0063 {
            get {
                return ResourceManager.GetString("M0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data inicial das ocorrências não definida.
        /// </summary>
        internal static string M0064 {
            get {
                return ResourceManager.GetString("M0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início do parcelamento deve ser especificada.
        /// </summary>
        internal static string M0065 {
            get {
                return ResourceManager.GetString("M0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de liquidacao maior que a data corrente.
        /// </summary>
        internal static string M0066 {
            get {
                return ResourceManager.GetString("M0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Soma dos itens diferente do valor total.
        /// </summary>
        internal static string M0067 {
            get {
                return ResourceManager.GetString("M0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel pagar parcial um lancamento parcelado.
        /// </summary>
        internal static string M0068 {
            get {
                return ResourceManager.GetString("M0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor parcial maior que o valor total.
        /// </summary>
        internal static string M0069 {
            get {
                return ResourceManager.GetString("M0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor parcial igual ao valor total.
        /// </summary>
        internal static string M0070 {
            get {
                return ResourceManager.GetString("M0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel liquidar um lancamento parcelado. As parcelas devem ser liquidadas individualmente.
        /// </summary>
        internal static string M0071 {
            get {
                return ResourceManager.GetString("M0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel parcelar lancamento com pagamento parcial.
        /// </summary>
        internal static string M0072 {
            get {
                return ResourceManager.GetString("M0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Senha não pode ficar em branco.
        /// </summary>
        internal static string M0073 {
            get {
                return ResourceManager.GetString("M0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova senha não pode ser em branco.
        /// </summary>
        internal static string M0074 {
            get {
                return ResourceManager.GetString("M0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação da senha não pode ser em branco.
        /// </summary>
        internal static string M0075 {
            get {
                return ResourceManager.GetString("M0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor parcial igual ao valor do lancamento. Va para liquidacao de lancamento ao inves de pagamento parcial.
        /// </summary>
        internal static string M0076 {
            get {
                return ResourceManager.GetString("M0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Soma dos percentuais de rateio maior do que 100.
        /// </summary>
        internal static string M0077 {
            get {
                return ResourceManager.GetString("M0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há nenhum registro com data de vencimento para a data atual.
        /// </summary>
        internal static string M0078 {
            get {
                return ResourceManager.GetString("M0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua pesquisa não retornou nenhum resultado - Tente outras opções de pesquisa.
        /// </summary>
        internal static string M0079 {
            get {
                return ResourceManager.GetString("M0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recebimento recorrente não pode ser parcelado.
        /// </summary>
        internal static string M0080 {
            get {
                return ResourceManager.GetString("M0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data inicial das ocorrências não definida.
        /// </summary>
        internal static string M0081 {
            get {
                return ResourceManager.GetString("M0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data nao pode ser maior do que a data corrente.
        /// </summary>
        internal static string M0082 {
            get {
                return ResourceManager.GetString("M0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A soma das parcelas nao bate com o valor total informado.
        /// </summary>
        internal static string M0083 {
            get {
                return ResourceManager.GetString("M0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um lancamento parcelado nao pode ter pagamento parcial.
        /// </summary>
        internal static string M0084 {
            get {
                return ResourceManager.GetString("M0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do pagamento parcial nao pode ser maior que o valor do lancamento.
        /// </summary>
        internal static string M0085 {
            get {
                return ResourceManager.GetString("M0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor parcial igual ao valor do lancamento. Va para liquidacao de lancamento ao inves de pagamento parcial.
        /// </summary>
        internal static string M0086 {
            get {
                return ResourceManager.GetString("M0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio nao pode ser menor que a data corrente.
        /// </summary>
        internal static string M0087 {
            get {
                return ResourceManager.GetString("M0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O numero de parcelas nao pode ser menor do que 2.
        /// </summary>
        internal static string M0088 {
            get {
                return ResourceManager.GetString("M0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel liquidar direto um lançamento parcelado. As parcelas devem ser liquidadas uma a uma..
        /// </summary>
        internal static string M0089 {
            get {
                return ResourceManager.GetString("M0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel fazer pagamento parcial de um lancamento parcelado.
        /// </summary>
        internal static string M0090 {
            get {
                return ResourceManager.GetString("M0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel parcelar um lancamento com pagamento parcial.
        /// </summary>
        internal static string M0091 {
            get {
                return ResourceManager.GetString("M0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data nao pode ser maior do que a data corrente.
        /// </summary>
        internal static string M0092 {
            get {
                return ResourceManager.GetString("M0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem notificações não lidas até esta data.
        /// </summary>
        internal static string M0093 {
            get {
                return ResourceManager.GetString("M0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem tarefas pendentes até esta data.
        /// </summary>
        internal static string M0094 {
            get {
                return ResourceManager.GetString("M0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de pagamento não informada.
        /// </summary>
        internal static string M0095 {
            get {
                return ResourceManager.GetString("M0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Soma dos percentuais de rateio maior do que 100.
        /// </summary>
        internal static string M0096 {
            get {
                return ResourceManager.GetString("M0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel liquidar um lancamento parcelado. As parcelas devem ser liquidadas individualmente.
        /// </summary>
        internal static string M0097 {
            get {
                return ResourceManager.GetString("M0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossivel excluir esta conta. Existem lancamentos de CONTAS A RECEBER vinculados a ela.
        /// </summary>
        internal static string M0098 {
            get {
                return ResourceManager.GetString("M0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido de compra já cadastrado.
        /// </summary>
        internal static string M0099 {
            get {
                return ResourceManager.GetString("M0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse pedido de compra. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0100 {
            get {
                return ResourceManager.GetString("M0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo anexado não pode ter nome maoir que 250 caracteres.
        /// </summary>
        internal static string M0101 {
            get {
                return ResourceManager.GetString("M0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem itens sem preço no pedido.
        /// </summary>
        internal static string M0103 {
            get {
                return ResourceManager.GetString("M0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem itens sem quantidade no pedido.
        /// </summary>
        internal static string M0104 {
            get {
                return ResourceManager.GetString("M0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem itens sem data de cotação no pedido.
        /// </summary>
        internal static string M0105 {
            get {
                return ResourceManager.GetString("M0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa de cancelamento e obrigatória.
        /// </summary>
        internal static string M0106 {
            get {
                return ResourceManager.GetString("M0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O login não pode ficar em branco.
        /// </summary>
        internal static string M0109 {
            get {
                return ResourceManager.GetString("M0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail já cadastrado.
        /// </summary>
        internal static string M0110 {
            get {
                return ResourceManager.GetString("M0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login já cadastrado.
        /// </summary>
        internal static string M0111 {
            get {
                return ResourceManager.GetString("M0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido de venda já cadastrado.
        /// </summary>
        internal static string M0112 {
            get {
                return ResourceManager.GetString("M0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse pedido de venda. Existem informações vinculadas a ele..
        /// </summary>
        internal static string M0113 {
            get {
                return ResourceManager.GetString("M0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum item incluído no pedido ou existem itens sem dados de cotação.
        /// </summary>
        internal static string M0114 {
            get {
                return ResourceManager.GetString("M0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa de cancelamento e obrigatória.
        /// </summary>
        internal static string M0115 {
            get {
                return ResourceManager.GetString("M0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem itens sem preço no pedido.
        /// </summary>
        internal static string M0116 {
            get {
                return ResourceManager.GetString("M0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem itens sem quantidade no pedido.
        /// </summary>
        internal static string M0117 {
            get {
                return ResourceManager.GetString("M0117", resourceCulture);
            }
        }
    }
}
