//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_CUSTO
    {
        public int CECU_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public string CECU_NR_NUMERO { get; set; }
        public string CECU_NM_NOME { get; set; }
        public int CECU_IN_ATIVO { get; set; }
        public Nullable<int> GRUP_CD_ID { get; set; }
        public Nullable<int> SUBG_CD_ID { get; set; }
        public Nullable<int> CECU_IN_TIPO { get; set; }
        public Nullable<int> CECU_IN_MOVTO { get; set; }
        public string CECU_NM_EXIBE { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        public virtual SUBGRUPO SUBGRUPO { get; set; }
    }
}
