//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_RECEBER_PARCELA
    {
        public int CRPA_CD_ID { get; set; }
        public int CARE_CD_ID { get; set; }
        public Nullable<int> CRPA_IN_PARCELA { get; set; }
        public Nullable<decimal> CRPA_VL_VALOR { get; set; }
        public Nullable<System.DateTime> CRPA_DT_VENCIMENTO { get; set; }
        public string CRPA_DS_DESCRICAO { get; set; }
        public Nullable<int> CRPA_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> CRPA_DT_QUITACAO { get; set; }
        public Nullable<decimal> CRPA_VL_RECEBIDO { get; set; }
        public Nullable<decimal> CRPA_VL_DESCONTO { get; set; }
        public Nullable<decimal> CRPA_VL_JUROS { get; set; }
        public Nullable<decimal> CRPA_VL_TAXAS { get; set; }
        public Nullable<int> CRPA_IN_QUITADA { get; set; }
        public string CRPA_NR_PARCELA { get; set; }
    
        public virtual CONTA_RECEBER CONTA_RECEBER { get; set; }
    }
}
