//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_RECEBER_TAG
    {
        public int CRTA_CD_ID { get; set; }
        public int CARE_CD_ID { get; set; }
        public int TITA_CD_ID { get; set; }
        public Nullable<int> CRTA_IN_ATIVO { get; set; }
        public string CRTA_NM_DESCRICAO { get; set; }
    
        public virtual CONTA_RECEBER CONTA_RECEBER { get; set; }
        public virtual TIPO_TAG TIPO_TAG { get; set; }
    }
}
