//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PAGAR_TAG
    {
        public int CPTA_CD_ID { get; set; }
        public int CAPA_CD_ID { get; set; }
        public int TITA_CD_ID { get; set; }
        public string CPTA_NM_DESCRICAO { get; set; }
        public Nullable<int> CPTA_IN_ATIVO { get; set; }
    
        public virtual CONTA_PAGAR CONTA_PAGAR { get; set; }
        public virtual TIPO_TAG TIPO_TAG { get; set; }
    }
}
