//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTA_PAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTA_PAGAR()
        {
            this.CONTA_PAGAR_ANEXO = new HashSet<CONTA_PAGAR_ANEXO>();
            this.CONTA_PAGAR_PARCELA = new HashSet<CONTA_PAGAR_PARCELA>();
            this.CONTA_PAGAR_RATEIO = new HashSet<CONTA_PAGAR_RATEIO>();
            this.CONTA_PAGAR_TAG = new HashSet<CONTA_PAGAR_TAG>();
        }
    
        public int CAPA_CD_ID { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public Nullable<int> COBA_CD_ID { get; set; }
        public Nullable<int> TIFA_CD_ID { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public Nullable<int> TITA_CD_ID { get; set; }
        public Nullable<int> FOPA_CD_ID { get; set; }
        public Nullable<int> PERI_CD_ID { get; set; }
        public Nullable<int> CECU_CD_ID { get; set; }
        public Nullable<System.DateTime> CAPA_DT_LANCAMENTO { get; set; }
        public Nullable<decimal> CAPA_VL_VALOR { get; set; }
        public string CAPA_DS_DESCRICAO { get; set; }
        public Nullable<int> CAPA_IN_TIPO_LANCAMENTO { get; set; }
        public string CAPA_NM_FAVORECIDO { get; set; }
        public string CAPA_NM_FORMA_PAGAMENTO { get; set; }
        public Nullable<int> CAPA_IN_LIQUIDADA { get; set; }
        public Nullable<int> CAPA_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> CAPA_DT_VENCIMENTO { get; set; }
        public Nullable<decimal> CAPA_VL_VALOR_PAGO { get; set; }
        public Nullable<System.DateTime> CAPA_DT_LIQUIDACAO { get; set; }
        public Nullable<int> CAPA_NR_ATRASO { get; set; }
        public string CAPA_TX_OBSERVACOES { get; set; }
        public Nullable<int> CAPA_IN_PARCELADA { get; set; }
        public Nullable<int> CAPA_IN_PARCELAS { get; set; }
        public Nullable<System.DateTime> CAPA_DT_INICIO_PARCELAS { get; set; }
        public Nullable<decimal> CAPA_VL_PARCELADO { get; set; }
        public string CAPA_NR_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> CAPA_DT_COMPETENCIA { get; set; }
        public Nullable<decimal> CAPA_VL_DESCONTO { get; set; }
        public Nullable<decimal> CAPA_VL_JUROS { get; set; }
        public Nullable<decimal> CAPA_VL_TAXAS { get; set; }
        public Nullable<decimal> CAPA_VL_SALDO { get; set; }
        public Nullable<int> CAPA_IN_PAGA_PARCIAL { get; set; }
        public Nullable<decimal> CAPA_VL_PARCIAL { get; set; }
        public Nullable<int> CAPA_IN_ABERTOS { get; set; }
        public Nullable<int> CAPA_IN_FECHADOS { get; set; }
        public Nullable<int> ASSI_CD_ID { get; set; }
        public Nullable<int> PECO_CD_ID { get; set; }
        public Nullable<int> COBA_CD_ID_1 { get; set; }
        public Nullable<int> CAPA_IN_CHEQUE { get; set; }
        public string CAPA_NR_CHEQUE { get; set; }
        public Nullable<int> CAPA_IN_TIPO_DOC { get; set; }
        public Nullable<System.DateTime> CAPA_DT_FINAL { get; set; }
    
        public virtual CENTRO_CUSTO CENTRO_CUSTO { get; set; }
        public virtual CONTA_BANCO CONTA_BANCO { get; set; }
        public virtual CONTA_BANCO CONTA_BANCO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_ANEXO> CONTA_PAGAR_ANEXO { get; set; }
        public virtual FORMA_PAGAMENTO FORMA_PAGAMENTO { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_PARCELA> CONTA_PAGAR_PARCELA { get; set; }
        public virtual PERIODICIDADE PERIODICIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_RATEIO> CONTA_PAGAR_RATEIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTA_PAGAR_TAG> CONTA_PAGAR_TAG { get; set; }
        public virtual TIPO_FAVORECIDO TIPO_FAVORECIDO { get; set; }
        public virtual TIPO_TAG TIPO_TAG { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
