//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPAMENTO_ANEXO
    {
        public int EQAN_CD_ID { get; set; }
        public int EQUI_CD_ID { get; set; }
        public string EQAN_NM_TITULO { get; set; }
        public System.DateTime EQAN_DT_ANEXO { get; set; }
        public int EQAN_IN_TIPO { get; set; }
        public string EQAN_AQ_ARQUIVO { get; set; }
        public int EQAN_IN_ATIVO { get; set; }
    
        public virtual EQUIPAMENTO EQUIPAMENTO { get; set; }
    }
}
