//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPAMENTO_MANUTENCAO
    {
        public int EQMA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public int EQUI_CD_ID { get; set; }
        public System.DateTime EQMA_DT_MANUTENCAO { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public string EQMA_TX_OBSERVACOES { get; set; }
        public int EQMA_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual EQUIPAMENTO EQUIPAMENTO { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
    }
}
