//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPAMENTO()
        {
            this.EQUIPAMENTO_ANEXO = new HashSet<EQUIPAMENTO_ANEXO>();
            this.EQUIPAMENTO_MANUTENCAO = new HashSet<EQUIPAMENTO_MANUTENCAO>();
        }
    
        public int EQUI_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> PERI_CD_ID { get; set; }
        public Nullable<int> CAEQ_CD_ID { get; set; }
        public string EQUI_NR_NUMERO { get; set; }
        public string EQUI_NM_NOME { get; set; }
        public string EQUI_DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> EQUI_DT_COMPRA { get; set; }
        public Nullable<decimal> EQUI_VL_VALOR { get; set; }
        public Nullable<int> EQUI_NR_VIDA_UTIL { get; set; }
        public Nullable<System.DateTime> EQUI_DT_BAIXA { get; set; }
        public string EQUI_DS_MOTIVO_BAIXA { get; set; }
        public int EQUI_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> EQUI_DT_CADASTRO { get; set; }
        public string EQUI_AQ_FOTO { get; set; }
        public Nullable<System.DateTime> EQUI_DT_MANUTENCAO { get; set; }
        public Nullable<int> EQUI_IN_AVISA_MANUTENCAO { get; set; }
        public string EQUI_TX_OBSERVACOES { get; set; }
        public Nullable<int> EQUI_IN_DEPRECIADOS { get; set; }
        public Nullable<int> EQUI_IN_MANUTENCAO { get; set; }
        public Nullable<int> EQUI_IN_BAIXADOS { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual CATEGORIA_EQUIPAMENTO CATEGORIA_EQUIPAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPAMENTO_ANEXO> EQUIPAMENTO_ANEXO { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPAMENTO_MANUTENCAO> EQUIPAMENTO_MANUTENCAO { get; set; }
        public virtual PERIODICIDADE PERIODICIDADE { get; set; }
    }
}
