//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR_MENSAGEM
    {
        public int FOME_CD_ID { get; set; }
        public int FORN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public int TIME_CD_ID { get; set; }
        public System.DateTime FOME_DT_ENVIO { get; set; }
        public string FOME_DS_TEXTO { get; set; }
        public Nullable<int> FOME_IN_ATIVO { get; set; }
        public Nullable<int> FOME_IN_ENVIADO { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual TIPO_MENSAGEM TIPO_MENSAGEM { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
