//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR_COMENTARIO
    {
        public int FOCM_CD_ID { get; set; }
        public int FORN_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> FOCM_DT_COMENTARIO { get; set; }
        public string FOCM_DS_COMENTARIO { get; set; }
        public Nullable<int> FOCM_IN_ATIVO { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
