//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PEDIDO_COMPRA
    {
        public int ITPC_CD_ID { get; set; }
        public int PECO_CD_ID { get; set; }
        public Nullable<int> PROD_CD_ID { get; set; }
        public Nullable<int> UNID_CD_ID { get; set; }
        public int ITPC_QN_QUANTIDADE { get; set; }
        public Nullable<decimal> ITPC_VL_PRECO_SELECIONADO { get; set; }
        public Nullable<int> ITPC_NR_QUANTIDADE_REVISADA { get; set; }
        public string ITPC_TX_OBSERVACOES { get; set; }
        public int ITPC_IN_ATIVO { get; set; }
        public Nullable<int> FORN_CD_ID { get; set; }
        public Nullable<System.DateTime> ITPC_DT_COTACAO { get; set; }
        public Nullable<int> ITPC_IN_TIPO { get; set; }
        public string ITPC_DS_JUSTIFICATIVA { get; set; }
        public Nullable<int> ITPC_NR_QUANTIDADE_RECEBIDA { get; set; }
    
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual PEDIDO_COMPRA PEDIDO_COMPRA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual UNIDADE UNIDADE { get; set; }
    }
}
