//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTO_ESTOQUE_PRODUTO
    {
        public int MOEP_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public int PROD_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public System.DateTime MOEP_DT_MOVIMENTO { get; set; }
        public int MOEP_IN_TIPO_MOVIMENTO { get; set; }
        public int MOEP_QN_QUANTIDADE { get; set; }
        public string MOEP_IN_ORIGEM { get; set; }
        public int MOEP_IN_CHAVE_ORIGEM { get; set; }
        public int MOEP_IN_ATIVO { get; set; }
        public string MOEP_DS_JUSTIFICATIVA { get; set; }
        public Nullable<int> MOEP_QN_ANTES { get; set; }
        public Nullable<int> MOEP_QN_DEPOIS { get; set; }
        public Nullable<int> MOEP_QN_ALTERADA { get; set; }
        public Nullable<int> MOEP_IN_OPERACAO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
