//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_VENDA_PARCELA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO_VENDA_PARCELA()
        {
            this.PEDIDO_VENDA1 = new HashSet<PEDIDO_VENDA>();
        }
    
        public int PVPC_CD_ID { get; set; }
        public int PEVE_CD_ID { get; set; }
        public Nullable<System.DateTime> PVPC_DT_VENCIMENTO_PARCELA { get; set; }
        public Nullable<int> PVPC_IN_PARCELA { get; set; }
        public Nullable<decimal> PVPC_VL_PARCELA { get; set; }
        public Nullable<int> PVPC_IN_ATIVO { get; set; }
    
        public virtual PEDIDO_VENDA PEDIDO_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_VENDA> PEDIDO_VENDA1 { get; set; }
    }
}
