//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_COMPRA_ACOMPANHAMENTO
    {
        public int PCAT_CD_ID { get; set; }
        public int PECO_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public string PCAT_DS_ACOMPANHAMENTO { get; set; }
        public int PCAT_IN_ATIVO { get; set; }
        public Nullable<System.DateTime> PCAT_DT_ACOMPANHAMENTO { get; set; }
    
        public virtual PEDIDO_COMPRA PEDIDO_COMPRA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
