//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTADORA_ANEXO
    {
        public int TRAX_CD_ID { get; set; }
        public int TRAN_CD_ID { get; set; }
        public string TRAX_NM_TITULO { get; set; }
        public System.DateTime TRAX_DT_ANEXO { get; set; }
        public int TRAX_IN_TIPO { get; set; }
        public string TRAX_AQ_ARQUIVO { get; set; }
        public int TRAX_IN_ATIVO { get; set; }
    
        public virtual TRANSPORTADORA TRANSPORTADORA { get; set; }
    }
}
