//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTADORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSPORTADORA()
        {
            this.TRANSPORTADORA_ANEXO = new HashSet<TRANSPORTADORA_ANEXO>();
        }
    
        public int TRAN_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> FILI_CD_ID { get; set; }
        public Nullable<int> TIVE_CD_ID { get; set; }
        public Nullable<int> TITR_CD_ID { get; set; }
        public string TRAN_NM_NOME { get; set; }
        public string TRAN_NM_RAZAO { get; set; }
        public string TRAN_NR_CNPJ { get; set; }
        public string TRAN_NM_EMAIL { get; set; }
        public string TRAN_NR_TELEFONES { get; set; }
        public string TRAN_NM_CONTATOS { get; set; }
        public string TRAN_NM_ENDERECO { get; set; }
        public string TRAN_NM_BAIRRO { get; set; }
        public string TRAN_NM_CIDADE { get; set; }
        public string TRAN_SG_UF { get; set; }
        public string TRAN_NR_CEP { get; set; }
        public System.DateTime TRAN_DT_CADASTRO { get; set; }
        public int TRAN_IN_ATIVO { get; set; }
        public string TRAN_NR_INSCRICAO_ESTADUAL { get; set; }
        public string TRAN_NR_INSCRICAO_MUNICIPAL { get; set; }
        public string TRAN_NM_WEBSITE { get; set; }
        public string TRAN_AQ_LOGO { get; set; }
        public string TRAN_TX_OBSERVACOES { get; set; }
        public string TRAN_DS_INFORMACOES_GERAIS { get; set; }
        public string TRAN_DS_AREA_COBERTURA { get; set; }
        public string TRAN_DS_TRANSPORTE_ESPECIAL { get; set; }
        public string TRAN_DS_SEGURO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual FILIAL FILIAL { get; set; }
        public virtual TIPO_TRANSPORTE TIPO_TRANSPORTE { get; set; }
        public virtual TIPO_VEICULO TIPO_VEICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSPORTADORA_ANEXO> TRANSPORTADORA_ANEXO { get; set; }
    }
}
