//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_FUNCIONARIO
    {
        public int USFU_CD_ID { get; set; }
        public int USUA_CD_ID { get; set; }
        public Nullable<System.DateTime> USFU_DT_NASCIMENTO { get; set; }
        public string USFU_NM_PAI { get; set; }
        public string USFU_NM_MAE { get; set; }
        public string USFU_NM_NATURALIDADE { get; set; }
        public string USFU_SG_UF_NATURALIDADE { get; set; }
        public string USFU_NM_NACIONALIDADE { get; set; }
        public string USFU_NM_TIPO_SANGUINEO { get; set; }
        public string USFU_NM_FATOR_RH { get; set; }
        public Nullable<System.DateTime> USFU_DT_EMISSAO_RG { get; set; }
        public string USFU_NM_ORGAO_RG { get; set; }
        public string USFU_SG_UF_RG { get; set; }
        public string USFU_NR_NIS { get; set; }
        public string USFU_NR_TITULO_ELEITOR { get; set; }
        public Nullable<System.DateTime> USFU_DT_TITULO_ELEITOR { get; set; }
        public string USFU_NR_TITULO_ELEITOR_ZONA { get; set; }
        public string USFU_NR_TITULO_ELEITOR_SECAO { get; set; }
        public string USFU_NM_TITULO_ELEITOR_MUNICIPIO { get; set; }
        public string USFU_SG__TITULO_ELEITOR_UF { get; set; }
        public string USFU_NR_CTPS { get; set; }
        public Nullable<System.DateTime> USFU_DT_CTPS { get; set; }
        public string USFU_NR_CTPS_SERIE { get; set; }
        public string USFU_SG_CTPS_UF { get; set; }
        public string USFU_NR_IDENTIDADE_CLASSE { get; set; }
        public string USFU_NM_ORGAO_CLASSE { get; set; }
        public Nullable<System.DateTime> USFU_DT_IDENTIDADE_CLASSE_EMISSAO { get; set; }
        public string USFU_NR_RESERVISTA { get; set; }
        public Nullable<System.DateTime> USFU_DT_RESERVISTA_DATA { get; set; }
        public string USFU_NM_RESERVISTA_CATEGORIA { get; set; }
        public string USFU_NM_ORGANIZACAO_MILITAR { get; set; }
        public string USFU_NR_CNH { get; set; }
        public Nullable<System.DateTime> USFU_DT_CNH_EMISSAO { get; set; }
        public Nullable<System.DateTime> USFU_DT_CNH_VALIDADE { get; set; }
        public string USFU_NM_CNH_CATEGORIA { get; set; }
        public string USFU_NR_CNS { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
